project_name: mallet
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: mallet
    ldflags:
      - -s -w
      - -X github.com/jpillora/chisel/share.BuildVersion=1.6.0
      - -X github.com/ryotarai/mallet/pkg/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
archives:
  - format: tar.gz
release:
  prerelease: auto
